version: '3.8'

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    env_file:
      - .env
    volumes:
      - influxdb-data:/var/lib/influxdb:rw
    restart: always
  telegraf:
    image: telegraf:latest
    container_name: telegraf
    depends_on:
      - influxdb
    network_mode: host
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    environment:
      - HOSTNAME=telegraf
    env_file:
      - .env
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    env_file:
      - .env
    restart: always

volumes:
  influxdb-data:
  grafana-data:
